<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE group [
<!ELEMENT group (student*)>
<!ELEMENT student (subject*,average?)>
<!ATTLIST student
        firstname CDATA #REQUIRED
        lastname CDATA #REQUIRED
        groupnumber CDATA #REQUIRED
        >
<!ELEMENT subject EMPTY>
<!ATTLIST subject
        title CDATA #REQUIRED
        mark (1|2|3|4|5) #REQUIRED
        >
<!ELEMENT average (#PCDATA)>
]>
<group>
    <student firstname="Peter" lastname="Penn" groupnumber="IT-01">
        <subject title="Arithmetic" mark="4"/>
        <subject title="History" mark="5"/>
        <subject title="Geography" mark="3"/>
        <subject title="English" mark="4"/>
        <average>4.0</average>
    </student>
    <student firstname="Luke" lastname="Skywalker" groupnumber="IT-01">
        <subject title="Arithmetic" mark="4"/>
        <subject title="History" mark="3"/>
        <subject title="Geography" mark="3"/>
        <subject title="English" mark="4"/>
        <average>3.5</average>
    </student>
</group>